version: '3'
services:
  bedrock_server:
    image: defektive/bedrock-server:latest
    ports:
      - 19132:19132/udp
    volumes:
      - mcpe_worlds:/tmp/worlds
      - ./data/downloads:/home/bedrock/downloads
      - ./data/worlds:/home/bedrock/bedrock_server/worlds
      - ./data/server.properties:/home/bedrock/bedrock_server/server.properties
      - ./data/permissions.json:/home/bedrock/bedrock_server/permissions.json
      - ./data/whitelist.json:/home/bedrock/bedrock_server/whitelist.json

  map_server:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./data/html:/usr/share/nginx/html:ro

  ofelia:
    image:  mcuadros/ofelia:latest
    volumes:
      - ./data/ofelia:/etc/ofelia
      - /var/run/docker.sock:/var/run/docker.sock

  mcpe_viz:
    image: defektive/mcpe-viz:latest
    volumes:
      - ./data/html:/tmp/out/
      - mcpe_worlds:/tmp/worlds/
    command: tail -f /dev/null

volumes:
  mcpe_worlds: {}
